###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
spring:
  application:
    ####注册中心应用名称
    name: config-server
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: https://github.com/wy130/springcloud-config.git
          ####搜索目录
          search-paths:
          - gkconfig
          force-pull: true
          timeout: 10
      ####读取分支
      label: master
####端口号
server:
  port: 8888


management:
  security:
  enabled: false
  endpoints:
    web:
      exposure:
        include: refresh
